x = "N/A"
s = "Special"

cardname = {
    0:x, 
    1:"Animate Wall", 
    2:"Armageddon", 
    3:"Balance", 
    4:"Benalish Hero", 
    5:"Black Ward", 
    6:"Blaze of Glory", 
    7:"Blessing", 
    8:"Blue Ward", 
    9:"Castle", 
    10:"Circle of Protection: Blue",
    11:"Circle of Protection: Green", 
    12:"Circle of Protection: Red",
    13:"Circle of Protection: White", 
    14:"Consecrate Land", 
    15:"Conversion", 
    16:"Crusade",
    17:"Death Ward", 
    18:"Disenchant", 
    19:"Farmstead", 
    20:"Green Ward", 
    21:"Guardian Angel",
    22:"Healing Salve", 
    23:"Holy Armor", 
    24:"Holy Strength", 
    25:"Island Sanctuary", 
    26:"Karma", 
    27:"Lance", 
    28:"Mesa Pegasus", 
    29:"Northern Paladin", 
    30:"Pearled Unicorn", 
    31:"Personal Incarnation", 
    32:"Purelace", 
    33:"Red Ward", 
    34:"Resurrection", 
    35:"Reverse Damage",
    36:"Righteouness", 
    37:"Samite Healer", 
    38:"Savannah Lions", 
    39:"Serra Angel", 
    40:"Swords to Plowshares", 
    41:"Veteran Bodyguard", 
    42:"Wall of Swords", 
    43:"White Knight",
    44:"White Ward", 
    45:"Wrath of God", 
    46:"Air Elemental", 
    47:"Ancestral Recall", 
    48:"Animate Artifact", 
    49:"Blue Element Blast", 
    50:"Braingeyser",
    51:"Clone",
    52:"Control Magic",
    53:"Copy Artifact",
    54:"Counter Spell",
    55:"Creature Bond",
    56:"Drain Power",
    57:"Feedback",
    58:"Flight",
    59:"Invisibility",
    60:"Jump",
    61:"Lifetap",
    62:"Lord of Atlantis",
    63:"Magical Hack",
    64:"Mahamoti Djinn",
    65:"Mana Short",
    66:"Merfolk of the Pearl Trident",
    67:"Phantasmal Forces",
    68:"Phantasmal Terrain",
    69:"Phantom Monster",
    70:"Pirate Ship",
    71:"Power Leak",
    72:"Power Sink",
    73:"Prodigal Sorcerer",
    74:"Psionic Blast",
    75:"Psychic Venom",
    76:"Sea Serpent",
    77:"Siren's Call",
    78:"Sleight of Mind",
    79:"Spell Blast",
    80:"Stasis",
    81:"Steal Artifact",
    82:"Thoughtlace",
    83:"Time Walk",
    84:"Time Twister",
    85:"Twidle",
    86:"Unsummon",
    87:"Vesuvan Doppelganger",
    88:"Volcanic Eruption",
    89:"Wall of Air",
    90:"Wall of Water",
    91:"Water Elemental",
    92:"Animate Dead",
    93:"Bad Moon",
    94:"Black Knight",
    95:"Bog Wraith",
    96:"Contract from Below",
    97:"Cursed Land",
    98:"Dark Ritual",
    99:"Darkpact",
    100:"Deathgrip",
    101:"Deathlace",
    102:"Demonic Attorney",
    103:"Demonic Hordes",
    104:"Demonic Tutor",
    105:"Drain Life",
    106:"Drudge Skeletons",
    107:"Evil Presence",
    108:"Fear",
    109:"Frozen Shade",
    110:"Gloom",
    111:"Howl from Beyond",
    112:"Hypnotic Specter ",
    113:"Lich",
    114:"Lord of the Pit",
    115:"Mind twist",
    116:"Nether Shadow",
    117:"Nettling Imp",
    118:"Nightmare",
    119:"Paralyze",
    120:"Pestilence",
    121:"Plague Rats",
    122:"Raise Dead",
    123:"Royal Assassin",
    124:"Sacrifice",
    125:"Scathe Zombies",
    126:"Scavenging Ghoul",
    127:"Sengir Vampire",
    128:"Simulacrum",
    129:"Sinkhole",
    130:"Terror",
    131:"Unholy Strength",
    132:"Wall of Bone",
    133:"Warp Artifact",
    134:"Weakness",
    135:"Will-o'-the-Wisp",
    136:"Word of Command",
    137:"Zombie Master",
    138:"Burrowing",
    139:"Chaoslace",
    140:"Disintegrate",
    141:"Dragon Whelp",
    142:"Dwarven Demolition Team",
    143:"Dwarven Warriors",
    144:"Earth Elemental",
    145:"Earthbind",
    146:"Earthquake",
    147:"False Orders",
    148:"Fire Elemental",
    149:"Fireball",
    150:"Firebreathing",
    151:"Flashfires",
    152:"Fork",
    153:"Goblin Balloon Brigade",
    154:"Goblin King",
    155:"Granite Gargoyle",
    156:"Gray Ogre",
    157:"Hill Giant",
    158:"Hurloon Minotaur",
    159:"Ironclaw Orcs",
    160:"Keldon Warlord",
    161:"Lightning Bolt",
    162:"Mana Flare",
    163:"Manabarbs",
    164:"Mons's Goblin Raiders",
    165:"Orcish Artillery",
    166:"Orcish Oriflamme",
    167:"Power Surge",
    168:"Raging River",
    169:"Red Elemental Blast",
    170:"Roc of Kher Ridges",
    171:"Rock Hydra",
    172:"Sedge Troll",
    173:"Shatter",
    174:"Shivan Dragon",
    175:"Smoke",
    176:"Stone Giant",
    177:"Stone Rain",
    178:"Tunnel",
    179:"Two-Headed Giant of Foriys",
    180:"Uthden Troll",
    181:"Wall of Fire",
    182:"Wall of Stone",
    183:"Wheel of Fortune",
    184:"Aspect of Wolf",
    185:"Berserk",
    186:"Birds of Paradise",
    187:"Camoflauge",
    188:"Channel",
    189:"Cockatrice",
    190:"Craw Wurm",
    191:"Elvish Archers",
    192:"Fastbond",
    193:"Fog",
    194:"Force of Nature",
    195:"Fungusaur",
    196:"Gaea's Liege",
    197:"Giant Growth",
    198:"Giant Spider",
    199:"Grizzly Bears",
    200:"Hurricane",
    201:"Ice Storm",
    202:"Instill Energy",
    203:"Ironroot Treefolk",
    204:"Kudzu",
    205:"Ley Druid",
    206:"Lifeforce",
    207:"Lifelace",
    208:"Living Artifact",
    209:"Living Lands",
    210:"Llanowar Elves",
    211:"Lure",
    212:"Natural Selection",
    213:"Regeneration",
    214:"Regrowth",
    215:"Scryb Sprites",
    216:"Shanodin Dryads",
    217:"Stream of Life",
    218:"Thicket Baselisk",
    219:"Timber Wolves",
    220:"Tranquility",
    221:"Tsunami",
    222:"Verduran Enchantress",
    223:"Wall of Brambles",
    224:"Wall of Ice",
    225:"Wall of Wood",
    226:"Wanderlust",
    227:"War Mammoth",
    228:"Web",
    229:"Wild Growth",
    230:"Ankh of Mishra",
    231:"Basalt Monalith",
    232:"Black Lotus",
    233:"Black Vise",
    234:"Celestial Prism",
    235:"Chaos Orb:",
    236:"Clockwork Beast",
    237:"Conservator",
    238:"Copper Tablet",
    239:"Crystal Rod",
    240:"Cyclopean Tomb",
    241:"Dingus Egg",
    242:"Disrupting Scepter",
    243:"Forcefield",
    244:"Gauntlet of Might",
    245:"Glasses of Urza",
    246:"Helm of Chatzuk",
    247:"Howling Mine",
    248:"Icy Manipulator",
    249:"Illusionary Mask",
    250:"Iron Star",
    251:"Ivory Cup",
    252:"Jade Monolith",
    253:"Jade Statue",
    254:"Jayemdae Tome",
    255:"Juggernaut",
    256:"Kormus Bell",
    257:"Library of Leng",
    258:"Living Wall",
    259:"Mana Vault",
    260:"Meekstone",
    261:"Mox Emerald",
    262:"Mox Jet",
    263:"Mox Pearl",
    264:"Mox Ruby",
    265:"Mox Saphire",
    266:"Nevinyrral's Disk",
    267:"Obsianus Golem",
    268:"Rod of Ruin",
    269:"Sol Ring",
    270:"Soul Net",
    271:"Sunglasses of Urza",
    272:"The Hive",
    273:"Throne of Bone",
    274:"Time Vault",
    275:"Winter Orb",
    276:"Wooden Sphere",
    277:"Badlands",
    278:"Bayou",
    279:"Plateau",
    280:"Savannah",
    281:"Scrublands",
    282:"Taiga",
    283:"Tropical Island",
    284:"Tundra",
    285:"Underground Sea",
    286:"Plains(A)",
    287:"Plains(B)",
    288:"Island(A)",
    289:"Island(B)",
    290:"Swamp(A)",
    291:"Swamp(B)",
    292:"Mountain(A)",
    293:"Mountain(B)",
    294:"Forest(A)",
    295:"Forest(B)"
}
cardpower = {
    "Animate Wall":x,
    "Armageddon":x,
    "Balance":x,
    "Benalish Hero":1,
    "Black Ward":x,
    "Blaze of Glory":x,
    "Blessing":x,
    "Blue Ward":x,
    "Castle":x,
    "Circle of Protection: Blue":x,
    "Circle of Protection: Green":x,
    "Circle of Protection: Red":x,
    "Circle of Protection: White":x,
    "Consecrate Land":x,
    "Conversion":x,
    "Crusade":x,
    "Death Ward":x,
    "Disenchant":x,
    "Farmstead":x,
    "Green Ward":x,
    "Guardian Angel":x,
    "Healing Salve":x,
    "Holy Armor":x,
    "Holy Strength":x,
    "Island Sanctuary":x,
    "Karma":x,
    "Lance":x,
    "Mesa Pegasus":1,
    "Northern Paladin":3,
    "Pearled Unicorn":2,
    "Personal Incarnation":6,
    "Purelace":x,
    "Red Ward":x,
    "Resurrection":x,
    "Reverse Damage":x,
    "Righteouness":x,
    "Samite Healer":1,
    "Savannah Lions":2,
    "Serra Angel":4,
    "Swords to Plowshares":x,
    "Veteran Bodyguard":2,
    "Wall of Swords":3,
    "White Knight":2,
    "White Ward":x,
    "Wrath of God":x,
    "Air Elemental":4,
    "Ancestral Recall":x,
    "Animate Artifact":x,
    "Blue Element Blast":x,
    "Braingeyser":x,
    "Clone":s,
    "Control Magic":x,
    "Copy Artifact":x,
    "Counter Spell":x,
    "Creature Bond":x,
    "Drain Power":x,
    "Feedback":x,
    "Flight":x,
    "Invisibility":x,
    "Jump":x,
    "Lifetap":x,
    "Lord of Atlantis":2,
    "Magical Hack":x,
    "Mahamoti Djinn":5,
    "Mana Short":x,
    "Merfolk of the Pearl Trident":1,
    "Phantasmal Forces":4,
    "Phantasmal Terrain":x,
    "Phantom Monster":3,
    "Pirate Ship":4,
    "Power Leak":x,
    "Power Sink":x,
    "Prodigal Sorcerer":1,
    "Psionic Blast":x,
    "Psychic Venom":x,
    "Sea Serpent":5,
    "Siren's Call":x,
    "Sleight of Mind":x,
    "Spell Blast":x,
    "Stasis":x,
    "Steal Artifact":x,
    "Thoughtlace":x,
    "Time Walk":x,
    "Time Twister":x,
    "Twidle":x,
    "Unsummon":x,
    "Vesuvan Doppelganger":s,
    "Volcanic Eruption":x,
    "Wall of Air":1,
    "Wall of Water":0,
    "Water Elemental":5,
    "Animate Dead":x,
    "Bad Moon":x,
    "Black Knight":2,
    "Bog Wraith":3,
    "Contract from Below":x,
    "Cursed Land":x,
    "Dark Ritual":x,
    "Darkpact":x,
    "Deathgrip":x,
    "Deathlace":x,
    "Demonic Attorney":x,
    "Demonic Hordes":5,
    "Demonic Tutor":x,
    "Drain Life":x,
    "Drudge Skeletons":1,
    "Evil Presence":x,
    "Fear":x,
    "Frozen Shade":0,
    "Gloom":x,
    "Howl from Beyond":x,
    "Hypnotic Specter ":2,
    "Lich":x,
    "Lord of the Pit":7,
    "Mind twist":x,
    "Nether Shadow":1,
    "Nettling Imp":1,
    "Nightmare":s,
    "Paralyze":x,
    "Pestilence":x,
    "Plague Rats":s,
    "Raise Dead":x,
    "Royal Assassin":1,
    "Sacrifice":x,
    "Scathe Zombies":2,
    "Scavenging Ghoul":2,
    "Sengir Vampire":4,
    "Simulacrum":x,
    "Sinkhole":x,
    "Terror":x,
    "Unholy Strength":x,
    "Wall of Bone":1,
    "Warp Artifact":x,
    "Weakness":x,
    "Will-o'-the-Wisp":0,
    "Word of Command":x,
    "Zombie Master":2,
    "Burrowing":x,
    "Chaoslace":x,
    "Disintegrate":x,
    "Dragon Whelp":2,
    "Dwarven Demolition Team":1,
    "Dwarven Warriors":1,
    "Earth Elemental":4,
    "Earthbind":x,
    "Earthquake":x,
    "False Orders":x,
    "Fire Elemental":5,
    "Fireball":x,
    "Firebreathing":x,
    "Flashfires":x,
    "Fork":x,
    "Goblin Balloon Brigade":1,
    "Goblin King":2,
    "Granite Gargoyle":2,
    "Gray Ogre":2,
    "Hill Giant":3,
    "Hurloon Minotaur":2,
    "Ironclaw Orcs":2,
    "Keldon Warlord":s,
    "Lightning Bolt":x,
    "Mana Flare":x,
    "Manabarbs":x,
    "Mons's Goblin Raiders":1,
    "Orcish Artillery":1,
    "Orcish Oriflamme":x,
    "Power Surge":x,
    "Raging River":x,
    "Red Elemental Blast":x,
    "Roc of Kher Ridges":3,
    "Rock Hydra":0,
    "Sedge Troll":2,
    "Shatter":x,
    "Shivan Dragon":5,
    "Smoke":x,
    "Stone Giant":3,
    "Stone Rain":x,
    "Tunnel":x,
    "Two-Headed Giant of Foriys":4,
    "Uthden Troll":2,
    "Wall of Fire":0,
    "Wall of Stone":0,
    "Wheel of Fortune":x,
    "Aspect of Wolf":x,
    "Berserk":x,
    "Birds of Paradise":0,
    "Camoflauge":x,
    "Channel":x,
    "Cockatrice":2,
    "Craw Wurm":6,
    "Elvish Archers":1,
    "Fastbond":x,
    "Fog":x,
    "Force of Nature":8,
    "Fungusaur":2,
    "Gaea's Liege":s,
    "Giant Growth":x,
    "Giant Spider":2,
    "Grizzly Bears":2,
    "Hurricane":x,
    "Ice Storm":x,
    "Instill Energy":x,
    "Ironroot Treefolk":3,
    "Kudzu":x,
    "Ley Druid":1,
    "Lifeforce":x,
    "Lifelace":x,
    "Living Artifact":x,
    "Living Lands":x,
    "Llanowar Elves":1,
    "Lure":x,
    "Natural Selection":x,
    "Regeneration":x,
    "Regrowth":x,
    "Scryb Sprites":1,
    "Shanodin Dryads":1,
    "Stream of Life":x,
    "Thicket Baselisk":2,
    "Timber Wolves":1,
    "Tranquility":x,
    "Tsunami":x,
    "Verduran Enchantress":0,
    "Wall of Brambles":2,
    "Wall of Ice":0,
    "Wall of Wood":0,
    "Wanderlust":x,
    "War Mammoth":3,
    "Web":x,
    "Wild Growth":x,
    "Ankh of Mishra":x,
    "Basalt Monalith":x,
    "Black Lotus":x,
    "Black Vise":x,
    "Celestial Prism":x,
    "Chaos Orb":x,
    "Clockwork Beast":0,
    "Conservator":x,
    "Copper Tablet":x,
    "Crystal Rod":x,
    "Cyclopean Tomb":x,
    "Dingus Egg":x,
    "Disrupting Scepter":x,
    "Forcefield":x,
    "Gauntlet of Might":x,
    "Glasses of Urza":x,
    "Helm of Chatzuk":x,
    "Howling Mine":x,
    "Icy Manipulator":x,
    "Illusionary Mask":x,
    "Iron Star":x,
    "Ivory Cup":x,
    "Jade Monolith":x,
    "Jade Statue":3,
    "Jayemdae Tome":x,
    "Juggernaut":5,
    "Kormus Bell":x,
    "Library of Leng":x,
    "Living Wall":0,
    "Mana Vault":x,
    "Meekstone":x,
    "Mox Emerald":x,
    "Mox Jet":x,
    "Mox Pearl":x,
    "Mox Ruby":x,
    "Mox Saphire":x,
    "Nevinyrral's Disk":x,
    "Obsianus Golem":4,
    "Rod of Ruin":x,
    "Sol Ring":x,
    "Soul Net":x,
    "Sunglasses of Urza":x,
    "The Hive":x,
    "Throne of Bone":x,
    "Time Vault":x,
    "Winter Orb":x,
    "Wooden Sphere":x,
    "Badlands":x,
    "Bayou":x,
    "Plateau":x,
    "Savannah":x,
    "Scrublands":x,
    "Taiga":x,
    "Tropical Island":x,
    "Tundra":x,
    "Underground Sea":x,
    "Plains(A)":x,
    "Plains(B)":x,
    "Island(A)":x,
    "Island(B)":x,
    "Swamp(A)":x,
    "Swamp(B)":x,
    "Mountain(A)":x,
    "Mountain(B)":x,
    "Forest(A)":x,
    "Forest(B)":x,
}

carddefence = {
    "Animate Wall":x,
    "Armageddon":x,
    "Balance":x,
    "Benalish Hero":1,
    "Black Ward":x,
    "Blaze of Glory":x,
    "Blessing":x,
    "Blue Ward":x,
    "Castle":x,
    "Circle of Protection: Blue":x,
    "Circle of Protection: Green":x,
    "Circle of Protection: Red":x,
    "Circle of Protection: White":x,
    "Consecrate Land":x,
    "Conversion":x,
    "Crusade":x,
    "Death Ward":x,
    "Disenchant":x,
    "Farmstead":x,
    "Green Ward":x,
    "Guardian Angel":x,
    "Healing Salve":x,
    "Holy Armor":x,
    "Holy Strength":x,
    "Island Sanctuary":x,
    "Karma":x,
    "Lance":x,
    "Mesa Pegasus":1,
    "Northern Paladin":3,
    "Pearled Unicorn":2,
    "Personal Incarnation":6,
    "Purelace":x,
    "Red Ward":x,
    "Resurrection":x,
    "Reverse Damage":x,
    "Righteouness":x,
    "Samite Healer":1,
    "Savannah Lions":1,
    "Serra Angel":4,
    "Swords to Plowshares":x,
    "Veteran Bodyguard":5,
    "Wall of Swords":5,
    "White Knight":2,
    "White Ward":x,
    "Wrath of God":x,
    "Air Elemental":4,
    "Ancestral Recall":x,
    "Animate Artifact":x,
    "Blue Element Blast":x,
    "Braingeyser":x,
    "Clone":s,
    "Control Magic":x,
    "Copy Artifact":x,
    "Counter Spell":x,
    "Creature Bond":x,
    "Drain Power":x,
    "Feedback":x,
    "Flight":x,
    "Invisibility":x,
    "Jump":x,
    "Lifetap":x,
    "Lord of Atlantis":2,
    "Magical Hack":x,
    "Mahamoti Djinn":6,
    "Mana Short":x,
    "Merfolk of the Pearl Trident":1,
    "Phantasmal Forces":1,
    "Phantasmal Terrain":x,
    "Phantom Monster":3,
    "Pirate Ship":3,
    "Power Leak":x,
    "Power Sink":x,
    "Prodigal Sorcerer":1,
    "Psionic Blast":x,
    "Psychic Venom":x,
    "Sea Serpent":5,
    "Siren's Call":x,
    "Sleight of Mind":x,
    "Spell Blast":x,
    "Stasis":x,
    "Steal Artifact":x,
    "Thoughtlace":x,
    "Time Walk":x,
    "Time Twister":x,
    "Twidle":x,
    "Unsummon":x,
    "Vesuvan Doppelganger":s,
    "Volcanic Eruption":x,
    "Wall of Air":5,
    "Wall of Water":5,
    "Water Elemental":4,
    "Animate Dead":x,
    "Bad Moon":x,
    "Black Knight":2,
    "Bog Wraith":3,
    "Contract from Below":x,
    "Cursed Land":x,
    "Dark Ritual":x,
    "Darkpact":x,
    "Deathgrip":x,
    "Deathlace":x,
    "Demonic Attorney":x,
    "Demonic Hordes":5,
    "Demonic Tutor":x,
    "Drain Life":x,
    "Drudge Skeletons":1,
    "Evil Presence":x,
    "Fear":x,
    "Frozen Shade":1,
    "Gloom":x,
    "Howl from Beyond":x,
    "Hypnotic Specter ":2,
    "Lich":x,
    "Lord of the Pit":7,
    "Mind twist":x,
    "Nether Shadow":1,
    "Nettling Imp":1,
    "Nightmare":s,
    "Paralyze":s,
    "Pestilence":x,
    "Plague Rats":x,
    "Raise Dead":x,
    "Royal Assassin":1,
    "Sacrifice":x,
    "Scathe Zombies":2,
    "Scavenging Ghoul":2,
    "Sengir Vampire":4,
    "Simulacrum":x,
    "Sinkhole":x,
    "Terror":x,
    "Unholy Strength":x,
    "Wall of Bone":4,
    "Warp Artifact":x,
    "Weakness":x,
    "Will-o'-the-Wisp":1,
    "Word of Command":x,
    "Zombie Master":3,
    "Burrowing":x,
    "Chaoslace":x,
    "Disintegrate":x,
    "Dragon Whelp":3,
    "Dwarven Demolition Team":1,
    "Dwarven Warriors":1,
    "Earth Elemental":5,
    "Earthbind":x,
    "Earthquake":x,
    "False Orders":x,
    "Fire Elemental":4,
    "Fireball":x,
    "Firebreathing":x,
    "Flashfires":x,
    "Fork":x,
    "Goblin Balloon Brigade":1,
    "Goblin King":2,
    "Granite Gargoyle":2,
    "Gray Ogre":2,
    "Hill Giant":3,
    "Hurloon Minotaur":3,
    "Ironclaw Orcs":2,
    "Keldon Warlord":s,
    "Lightning Bolt":x,
    "Mana Flare":x,
    "Manabarbs":x,
    "Mons's Goblin Raiders":1,
    "Orcish Artillery":3,
    "Orcish Oriflamme":x,
    "Power Surge":x,
    "Raging River":x,
    "Red Elemental Blast":x,
    "Roc of Kher Ridges":3,
    "Rock Hydra":0,
    "Sedge Troll":2,
    "Shatter":x,
    "Shivan Dragon":5,
    "Smoke":x,
    "Stone Giant":4,
    "Stone Rain":x,
    "Tunnel":x,
    "Two-Headed Giant of Foriys":4,
    "Uthden Troll":2,
    "Wall of Fire":5,
    "Wall of Stone":8,
    "Wheel of Fortune":x,
    "Aspect of Wolf":x,
    "Berserk":x,
    "Birds of Paradise":1,
    "Camoflauge":x,
    "Channel":x,
    "Cockatrice":4,
    "Craw Wurm":4,
    "Elvish Archers":2,
    "Fastbond":x,
    "Fog":x,
    "Force of Nature":8,
    "Fungusaur":2,
    "Gaea's Liege":s,
    "Giant Growth":x,
    "Giant Spider":4,
    "Grizzly Bears":2,
    "Hurricane":x,
    "Ice Storm":x,
    "Instill Energy":x,
    "Ironroot Treefolk":5,
    "Kudzu":x,
    "Ley Druid":1,
    "Lifeforce":x,
    "Lifelace":x,
    "Living Artifact":x,
    "Living Lands":x,
    "Llanowar Elves":1,
    "Lure":x,
    "Natural Selection":x,
    "Regeneration":x,
    "Regrowth":x,
    "Scryb Sprites":1,
    "Shanodin Dryads":1,
    "Stream of Life":x,
    "Thicket Baselisk":4,
    "Timber Wolves":1,
    "Tranquility":x,
    "Tsunami":x,
    "Verduran Enchantress":2,
    "Wall of Brambles":3,
    "Wall of Ice":7,
    "Wall of Wood":3,
    "Wanderlust":x,
    "War Mammoth":3,
    "Web":x,
    "Wild Growth":x,
    "Ankh of Mishra":x,
    "Basalt Monalith":x,
    "Black Lotus":x,
    "Black Vise":x,
    "Celestial Prism":x,
    "Chaos Orb":x,
    "Clockwork Beast":4,
    "Conservator":x,
    "Copper Tablet":x,
    "Crystal Rod":x,
    "Cyclopean Tomb":x,
    "Dingus Egg":x,
    "Disrupting Scepter":x,
    "Forcefield":x,
    "Gauntlet of Might":x,
    "Glasses of Urza":x,
    "Helm of Chatzuk":x,
    "Howling Mine":x,
    "Icy Manipulator":x,
    "Illusionary Mask":x,
    "Iron Star":x,
    "Ivory Cup":x,
    "Jade Monolith":x,
    "Jade Statue":6,
    "Jayemdae Tome":x,
    "Juggernaut":3,
    "Kormus Bell":x,
    "Library of Leng":x,
    "Living Wall":6,
    "Mana Vault":x,
    "Meekstone":x,
    "Mox Emerald":x,
    "Mox Jet":x,
    "Mox Pearl":x,
    "Mox Ruby":x,
    "Mox Saphire":x,
    "Nevinyrral's Disk":x,
    "Obsianus Golem":6,
    "Rod of Ruin":x,
    "Sol Ring":x,
    "Soul Net":x,
    "Sunglasses of Urza":x,
    "The Hive":x,
    "Throne of Bone":x,
    "Time Vault":x,
    "Winter Orb":x,
    "Wooden Sphere":x,
    "Badlands":x,
    "Bayou":x,
    "Plateau":x,
    "Savannah":x,
    "Scrublands":x,
    "Taiga":x,
    "Tropical Island":x,
    "Tundra":x,
    "Underground Sea":x,
    "Plains(A)":x,
    "Plains(B)":x,
    "Island(A)":x,
    "Island(B)":x,
    "Swamp(A)":x,
    "Swamp(B)":x,
    "Mountain(A)":x,
    "Mountain(B)":x,
    "Forest(A)":x,
    "Forest(B)":x,
}

cardtype = {
    "Animate Wall":"White",
    "Armageddon":"White",
    "Balance":"White",
    "Benalish Hero":"White",
    "Black Ward":"White",
    "Blaze of Glory":"White",
    "Blessing":"White",
    "Blue Ward":"White",
    "Castle":"White",
    "Circle of Protection: Blue":"White",
    "Circle of Protection: Green":"White",
    "Circle of Protection: Red":"White",
    "Circle of Protection: White":"White",
    "Consecrate Land":"White",
    "Conversion":"White",
    "Crusade":"White",
    "Death Ward":"White",
    "Disenchant":"White",
    "Farmstead":"White",
    "Green Ward":"White",
    "Guardian Angel":"White",
    "Healing Salve":"White",
    "Holy Armor":"White",
    "Holy Strength":"White",
    "Island Sanctuary":"White",
    "Karma":"White",
    "Lance":"White",
    "Mesa Pegasus":"White",
    "Northern Paladin":"White",
    "Pearled Unicorn":"White",
    "Personal Incarnation":"White",
    "Purelace":"White",
    "Red Ward":"White",
    "Resurrection":"White",
    "Reverse Damage":"White",
    "Righteouness":"White",
    "Samite Healer":"White",
    "Savannah Lions":"White",
    "Serra Angel":"White",
    "Swords to Plowshares":"White",
    "Veteran Bodyguard":"White",
    "Wall of Swords":"White",
    "White Knight":"White",
    "White Ward":"White",
    "Wrath of God":"White",
    "Air Elemental":"Blue",
    "Ancestral Recall":"Blue",
    "Animate Artifact":"Blue",
    "Blue Element Blast":"Blue",
    "Braingeyser":"Blue",
    "Clone":"Blue",
    "Control Magic":"Blue",
    "Copy Artifact":"Blue",
    "Counter Spell":"Blue",
    "Creature Bond":"Blue",
    "Drain Power":"Blue",
    "Feedback":"Blue",
    "Flight":"Blue",
    "Invisibility":"Blue",
    "Jump":"Blue",
    "Lifetap":"Blue",
    "Lord of Atlantis":"Blue",
    "Magical Hack":"Blue",
    "Mahamoti Djinn":"Blue",
    "Mana Short":"Blue",
    "Merfolk of the Pearl Trident":"Blue",
    "Phantasmal Forces":"Blue",
    "Phantasmal Terrain":"Blue",
    "Phantom Monster":"Blue",
    "Pirate Ship":"Blue",
    "Power Leak":"Blue",
    "Power Sink":"Blue",
    "Prodigal Sorcerer":"Blue",
    "Psionic Blast":"Blue",
    "Psychic Venom":"Blue",
    "Sea Serpent":"Blue",
    "Siren's Call":"Blue",
    "Sleight of Mind":"Blue",
    "Spell Blast":"Blue",
    "Stasis":"Blue",
    "Steal Artifact":"Blue",
    "Thoughtlace":"Blue",
    "Time Walk":"Blue",
    "Time Twister":"Blue",
    "Twidle":"Blue",
    "Unsummon":"Blue",
    "Vesuvan Doppelganger":"Blue",
    "Volcanic Eruption":"Blue",
    "Wall of Air":"Blue",
    "Wall of Water":"Blue",
    "Water Elemental":"Blue",
    "Animate Dead":"Black",
    "Bad Moon":"Black",
    "Black Knight":"Black",
    "Bog Wraith":"Black",
    "Contract from Below":"Black",
    "Cursed Land":"Black",
    "Dark Ritual":"Black",
    "Darkpact":"Black",
    "Deathgrip":"Black",
    "Deathlace":"Black",
    "Demonic Attorney":"Black",
    "Demonic Hordes":"Black",
    "Demonic Tutor":"Black",
    "Drain Life":"Black",
    "Drudge Skeletons":"Black",
    "Evil Presence":"Black",
    "Fear":"Black",
    "Frozen Shade":"Black",
    "Gloom":"Black",
    "Howl from Beyond":"Black",
    "Hypnotic Specter ":"Black",
    "Lich":"Black",
    "Lord of the Pit":"Black",
    "Mind twist":"Black",
    "Nether Shadow":"Black",
    "Nettling Imp":"Black",
    "Nightmare":"Black",
    "Paralyze":"Black",
    "Pestilence":"Black",
    "Plague Rats":"Black",
    "Raise Dead":"Black",
    "Royal Assassin":"Black",
    "Sacrifice":"Black",
    "Scathe Zombies":"Black",
    "Scavenging Ghoul":"Black",
    "Sengir Vampire":"Black",
    "Simulacrum":"Black",
    "Sinkhole":"Black",
    "Terror":"Black",
    "Unholy Strength":"Black",
    "Wall of Bone":"Black",
    "Warp Artifact":"Black",
    "Weakness":"Black",
    "Will-o'-the-Wisp":"Black",
    "Word of Command":"Black",
    "Zombie Master":"Black",
    "Burrowing":"Red",
    "Chaoslace":"Red",
    "Disintegrate":"Red",
    "Dragon Whelp":"Red",
    "Dwarven Demolition Team":"Red",
    "Dwarven Warriors":"Red",
    "Earth Elemental":"Red",
    "Earthbind":"Red",
    "Earthquake":"Red",
    "False Orders":"Red",
    "Fire Elemental":"Red",
    "Fireball":"Red",
    "Firebreathing":"Red",
    "Flashfires":"Red",
    "Fork":"Red",
    "Goblin Balloon Brigade":"Red",
    "Goblin King":"Red",
    "Granite Gargoyle":"Red",
    "Gray Ogre":"Red",
    "Hill Giant":"Red",
    "Hurloon Minotaur":"Red",
    "Ironclaw Orcs":"Red",
    "Keldon Warlord":"Red",
    "Lightning Bolt":"Red",
    "Mana Flare":"Red",
    "Manabarbs":"Red",
    "Mons's Goblin Raiders":"Red",
    "Orcish Artillery":"Red",
    "Orcish Oriflamme":"Red",
    "Power Surge":"Red",
    "Raging River":"Red",
    "Red Elemental Blast":"Red",
    "Roc of Kher Ridges":"Red",
    "Rock Hydra":"Red",
    "Sedge Troll":"Red",
    "Shatter":"Red",
    "Shivan Dragon":"Red",
    "Smoke":"Red",
    "Stone Giant":"Red",
    "Stone Rain":"Red",
    "Tunnel":"Red",
    "Two-Headed Giant of Foriys":"Red",
    "Uthden Troll":"Red",
    "Wall of Fire":"Red",
    "Wall of Stone":"Red",
    "Wheel of Fortune":"Red",
    "Aspect of Wolf":"Green",
    "Berserk":"Green",
    "Birds of Paradise":"Green",
    "Camoflauge":"Green",
    "Channel":"Green",
    "Cockatrice":"Green",
    "Craw Wurm":"Green",
    "Elvish Archers":"Green",
    "Fastbond":"Green",
    "Fog":"Green",
    "Force of Nature":"Green",
    "Fungusaur":"Green",
    "Gaea's Liege":"Green",
    "Giant Growth":"Green",
    "Giant Spider":"Green",
    "Grizzly Bears":"Green",
    "Hurricane":"Green",
    "Ice Storm":"Green",
    "Instill Energy":"Green",
    "Ironroot Treefolk":"Green",
    "Kudzu":"Green",
    "Ley Druid":"Green",
    "Lifeforce":"Green",
    "Lifelace":"Green",
    "Living Artifact":"Green",
    "Living Lands":"Green",
    "Llanowar Elves":"Green",
    "Lure":"Green",
    "Natural Selection":"Green",
    "Regeneration":"Green",
    "Regrowth":"Green",
    "Scryb Sprites":"Green",
    "Shanodin Dryads":"Green",
    "Stream of Life":"Green",
    "Thicket Baselisk":"Green",
    "Timber Wolves":"Green",
    "Tranquility":"Green",
    "Tsunami":"Green",
    "Verduran Enchantress":"Green",
    "Wall of Brambles":"Green",
    "Wall of Ice":"Green",
    "Wall of Wood":"Green",
    "Wanderlust":"Green",
    "War Mammoth":"Green",
    "Web":"Green",
    "Wild Growth":"Green",
    "Ankh of Mishra":"Artifact",
    "Basalt Monalith":"Artifact",
    "Black Lotus":"Artifact",
    "Black Vise":"Artifact",
    "Celestial Prism":"Artifact",
    "Chaos Orb":"Artifact",
    "Clockwork Beast":"Artifact",
    "Conservator":"Artifact",
    "Copper Tablet":"Artifact",
    "Crystal Rod":"Artifact",
    "Cyclopean Tomb":"Artifact",
    "Dingus Egg":"Artifact",
    "Disrupting Scepter":"Artifact",
    "Forcefield":"Artifact",
    "Gauntlet of Might":"Artifact",
    "Glasses of Urza":"Artifact",
    "Helm of Chatzuk":"Artifact",
    "Howling Mine":"Artifact",
    "Icy Manipulator":"Artifact",
    "Illusionary Mask":"Artifact",
    "Iron Star":"Artifact",
    "Ivory Cup":"Artifact",
    "Jade Monolith":"Artifact",
    "Jade Statue":"Artifact",
    "Jayemdae Tome":"Artifact",
    "Juggernaut":"Artifact",
    "Kormus Bell":"Artifact",
    "Library of Leng":"Artifact",
    "Living Wall":"Artifact",
    "Mana Vault":"Artifact",
    "Meekstone":"Artifact",
    "Mox Emerald":"Artifact",
    "Mox Jet":"Artifact",
    "Mox Pearl":"Artifact",
    "Mox Ruby":"Artifact",
    "Mox Saphire":"Artifact",
    "Nevinyrral's Disk":"Artifact",
    "Obsianus Golem":"Artifact",
    "Rod of Ruin":"Artifact",
    "Sol Ring":"Artifact",
    "Soul Net":"Artifact",
    "Sunglasses of Urza":"Artifact",
    "The Hive":"Artifact",
    "Throne of Bone":"Artifact",
    "Time Vault":"Artifact",
    "Winter Orb":"Artifact",
    "Wooden Sphere":"Artifact",
    "Badlands":"Land",
    "Bayou":"Land",
    "Plateau":"Land",
    "Savannah":"Land",
    "Scrublands":"Land",
    "Taiga":"Land",
    "Tropical Island":"Land",
    "Tundra":"Land",
    "Underground Sea":"Land",
    "Plains(A)":"Land",
    "Plains(B)":"Land",
    "Island(A)":"Land",
    "Island(B)":"Land",
    "Swamp(A)":"Land",
    "Swamp(B)":"Land",
    "Mountain(A)":"Land",
    "Mountain(B)":"Land",
    "Forest(A)":"Land",
    "Forest(B)":"Land",
}

coloredmanacost = {
    "Animate Wall":1,
    "Armageddon":1,
    "Balance":1,
    "Benalish Hero":1,
    "Black Ward":1,
    "Blaze of Glory":1,
    "Blessing":2,
    "Blue Ward":1,
    "Castle":1,
    "Circle of Protection: Blue":1,
    "Circle of Protection: Green":1,
    "Circle of Protection: Red":1,
    "Circle of Protection: White":1,
    "Consecrate Land":1,
    "Conversion":2,
    "Crusade":2,
    "Death Ward":1,
    "Disenchant":1,
    "Farmstead":3,
    "Green Ward":1,
    "Guardian Angel":1,
    "Healing Salve":1,
    "Holy Armor":1,
    "Holy Strength":1,
    "Island Sanctuary":1,
    "Karma":2,
    "Lance":1,
    "Mesa Pegasus":1,
    "Northern Paladin":2,
    "Pearled Unicorn":1,
    "Personal Incarnation":3,
    "Purelace":1,
    "Red Ward":1,
    "Resurrection":2,
    "Reverse Damage":2,
    "Righteouness":1,
    "Samite Healer":1,
    "Savannah Lions":1,
    "Serra Angel":2,
    "Swords to Plowshares":1,
    "Veteran Bodyguard":2,
    "Wall of Swords":1,
    "White Knight":2,
    "White Ward":1,
    "Wrath of God":2,
    "Air Elemental":2,
    "Ancestral Recall":1,
    "Animate Artifact":1,
    "Blue Element Blast":1,
    "Braingeyser":2,
    "Clone":1,
    "Control Magic":2,
    "Copy Artifact":1,
    "Counter Spell":2,
    "Creature Bond":1,
    "Drain Power":2,
    "Feedback":1,
    "Flight":1,
    "Invisibility":2,
    "Jump":1,
    "Lifetap":2,
    "Lord of Atlantis":2,
    "Magical Hack":1,
    "Mahamoti Djinn":2,
    "Mana Short":1,
    "Merfolk of the Pearl Trident":1,
    "Phantasmal Forces":1,
    "Phantasmal Terrain":2,
    "Phantom Monster":1,
    "Pirate Ship":1,
    "Power Leak":1,
    "Power Sink":1,
    "Prodigal Sorcerer":1,
    "Psionic Blast":1,
    "Psychic Venom":1,
    "Sea Serpent":1,
    "Siren's Call":1,
    "Sleight of Mind":1,
    "Spell Blast":1,
    "Stasis":1,
    "Steal Artifact":2,
    "Thoughtlace":1,
    "Time Walk":1,
    "Time Twister":1,
    "Twidle":1,
    "Unsummon":1,
    "Vesuvan Doppelganger":2,
    "Volcanic Eruption":3,
    "Wall of Air":2,
    "Wall of Water":2,
    "Water Elemental":2,
    "Animate Dead":1,
    "Bad Moon":1,
    "Black Knight":2,
    "Bog Wraith":1,
    "Contract from Below":1,
    "Cursed Land":2,
    "Dark Ritual":1,
    "Darkpact":3,
    "Deathgrip":2,
    "Deathlace":1,
    "Demonic Attorney":2,
    "Demonic Hordes":3,
    "Demonic Tutor":1,
    "Drain Life":1,
    "Drudge Skeletons":1,
    "Evil Presence":1,
    "Fear":2,
    "Frozen Shade":1,
    "Gloom":1,
    "Howl from Beyond":1,
    "Hypnotic Specter ":2,
    "Lich":4,
    "Lord of the Pit":3,
    "Mind twist":1,
    "Nether Shadow":2,
    "Nettling Imp":1,
    "Nightmare":1,
    "Paralyze":1,
    "Pestilence":2,
    "Plague Rats":1,
    "Raise Dead":1,
    "Royal Assassin":2,
    "Sacrifice":1,
    "Scathe Zombies":1,
    "Scavenging Ghoul":1,
    "Sengir Vampire":2,
    "Simulacrum":1,
    "Sinkhole":2,
    "Terror":1,
    "Unholy Strength":1,
    "Wall of Bone":1,
    "Warp Artifact":2,
    "Weakness":1,
    "Will-o'-the-Wisp":1,
    "Word of Command":2,
    "Zombie Master":2,
    "Burrowing":1,
    "Chaoslace":1,
    "Disintegrate":1,
    "Dragon Whelp":2,
    "Dwarven Demolition Team":1,
    "Dwarven Warriors":1,
    "Earth Elemental":2,
    "Earthbind":1,
    "Earthquake":1,
    "False Orders":1,
    "Fire Elemental":2,
    "Fireball":1,
    "Firebreathing":1,
    "Flashfires":1,
    "Fork":2,
    "Goblin Balloon Brigade":1,
    "Goblin King":2,
    "Granite Gargoyle":1,
    "Gray Ogre":1,
    "Hill Giant":1,
    "Hurloon Minotaur":2,
    "Ironclaw Orcs":1,
    "Keldon Warlord":2,
    "Lightning Bolt":1,
    "Mana Flare":1,
    "Manabarbs":1,
    "Mons's Goblin Raiders":1,
    "Orcish Artillery":1,
    "Orcish Oriflamme":1,
    "Power Surge":2,
    "Raging River":2,
    "Red Elemental Blast":1,
    "Roc of Kher Ridges":1,
    "Rock Hydra":2,
    "Sedge Troll":1,
    "Shatter":1,
    "Shivan Dragon":2,
    "Smoke":2,
    "Stone Giant":2,
    "Stone Rain":1,
    "Tunnel":1,
    "Two-Headed Giant of Foriys":1,
    "Uthden Troll":1,
    "Wall of Fire":2,
    "Wall of Stone":2,
    "Wheel of Fortune":1,
    "Aspect of Wolf":1,
    "Berserk":1,
    "Birds of Paradise":1,
    "Camoflauge":1,
    "Channel":2,
    "Cockatrice":2,
    "Craw Wurm":2,
    "Elvish Archers":1,
    "Fastbond":1,
    "Fog":1,
    "Force of Nature":4,
    "Fungusaur":1,
    "Gaea's Liege":3,
    "Giant Growth":1,
    "Giant Spider":1,
    "Grizzly Bears":1,
    "Hurricane":1,
    "Ice Storm":1,
    "Instill Energy":1,
    "Ironroot Treefolk":1,
    "Kudzu":2,
    "Ley Druid":1,
    "Lifeforce":2,
    "Lifelace":1,
    "Living Artifact":1,
    "Living Lands":1,
    "Llanowar Elves":1,
    "Lure":2,
    "Natural Selection":1,
    "Regeneration":1,
    "Regrowth":1,
    "Scryb Sprites":1,
    "Shanodin Dryads":1,
    "Stream of Life":1,
    "Thicket Baselisk":2,
    "Timber Wolves":1,
    "Tranquility":1,
    "Tsunami":1,
    "Verduran Enchantress":2,
    "Wall of Brambles":1,
    "Wall of Ice":1,
    "Wall of Wood":1,
    "Wanderlust":1,
    "War Mammoth":1,
    "Web":1,
    "Wild Growth":1,
}

othermanacost = {

}

def getcname(cnum):
    return(cardname[cnum])

def getcpower(cname):
    return(cardpower[cname])

def getcdefence(cname):
    return(carddefence[cname])

def getctype(cname):
    return(cardtype[cname])

def getcmcost(cname):
    return(coloredmanacost[cname])

def getomcost(cname):
    return(othermanacost[cname])